learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('users/', include('users.urls')),
    ]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""
from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all topics,
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),  # /<int:topic_id>/ busca un integer, lo guarda en la variable
    # Page for adding a new Topic                                topic_id y lo va a utilizar la funcion topic() en views
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),  # <int:topic_id> captures a numerical value and assigns it to the variable topic_id
    # Page for editing an entry.
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    # Page for deleting an entry
    path('delete_entry/<int:entry_id>', views.delete_entry, name='delete_entry'),
    ]

users/urls.py
"""Defines URL patterns for learning_logs."""
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # hay varias urls que tiene django para usuarios, login, logout, etc
    path('', include('django.contrib.auth.urls')),
    # registration page
    path('register/', views.register, name='register'),
    ]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User  # importo el model User que tiene django
# Create your models here.


class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)  # You use CharField when you want to store a small amount of text
    date_added = models.DateTimeField(auto_now_add=True)  # cuando se crea el Topic automaticamente se llena este campo con la fecha y hora actual
    owner = models.ForeignKey(User, on_delete=models.CASCADE)  # aca designo una relacion del topic con un user, si se borra el user se borra el topic

    def __str__(self):
        """Return a string representation of the model"""
        return self.text  # Django calls a __str__() method to display a simple representation of a model


class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)  # primero dice que el topic es un objeto Topic y on_delete sirve para
    text = models.TextField()    # indicar que hacer si se borra el objeto referenciado (que hacer con los entries si se borra el Topic)
    date_added = models.DateTimeField(auto_now_add=True)  # models.CASCADE hace que si se borra un topic se borren todas sus entries.
                                                    # es algo de SQL (no de Django). En internet (stackoverflow) se pueden ver otras opciones

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of a model"""
        if len(self.text) > 50:
            frase = self.text[:50] + "..."
        else:
            frase = self.text
        return frase

learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):  # hereda .ModelForms de forms
    class Meta:  # The simplest version of a ModelForm consists of a nested Meta class telling Django which model to base the form on and which fields to include in the form
        model = Topic  # we build a form from the Topic model and include only the text field
        fields = ['text']  # que campos del modelo toma
        labels = {'text': ''}  # le dice a djanog que genere una etiqueta pata el campo texto, en este caso que no genere nada


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}  # es la forma que toma el elemento form, por defecto en django es text
                                                                # pero aca lo hacemos que sea textarea, para que sea un rectangulo mas grande
                                                                # y que tenga 80 columndas, por defecto vienen 40

learning_logs/views.py
from django.shortcuts import render, redirect
from .models import Topic, Entry  # We first import the model associated with the data we need
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required # decorators son directivas que se escriben antes de una funcion para modificar un toque su comportamiento
from django.http import Http404


def index(request):
    """The home page for Learning Log"""
    return render(request, 'learning_logs/index.html')


def check_owner(request, topic):
    if topic.owner != request.user:  # se asegura que el topic pertence al usuario actual
        raise Http404   # si un usuario quiere acceder a la url de un topic que no le pertenece, salta un error de pagina no encontrada


@login_required  # aca uso el decorator login_required para que solo los usuarios logeados puedan acceder a topics
def topics(request):  # function needs one parameter: the request object Django received from the server
    """Show all topics"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')  # cuando un usuario se logea el objeto request tiene un atributo user, aca se muestran solo los topics en los que el atributo owner de Topic (en models) sea igual al atributo user de la request.
    context = {'topics': topics}  # es el diccionario que se manda a los templates
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    check_owner(request, topic)
    entries = topic.entry_set.order_by('-date_added')  # el - hace que los ordene al reves, el mas reciente primero.
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """Add a new topic"""
    if request.method != 'POST':  # puede ser POST o GET
        # no data submitted; create a blank form.
        form = TopicForm
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)  # commite=false hace que no se guarde en la base de datos, pero que quede en la variable new_topic
            new_topic.owner = request.user  # aca le asigno un owner al topic, claramente el usuario que hace la request
            new_topic.save()        # aca si se guarda en la base de datos
            return redirect('learning_logs:topics')
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
    check_owner(request, topic)
    if request.method != 'POST':
        # No data submitted, create a blank form.
        form = EntryForm()
    else:
        # POST data submitted, process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)  # se crea un objeto Entry con los datos ingresados por el usuario pero no se guarda en la base de datos (commit=False)
            new_entry.topic = topic        # porque antes hay que darle valor a "topic" (un atributo de Entry)
            new_entry.save()           # ahora new_entry SI tiene todos los atributos (topic, text y date_added (que se genera automaticamente) completos.
            return redirect('learning_logs:topic', topic_id=topic_id)  # topic_id explicado en notas.txt
    # Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:  # chequea que atributo owner de topic sea igual que el atributo user del objeto request.
        raise Http404
    if request.method != 'POST':
        # Initial request, pre-fill form with the current entry.
        form = EntryForm(instance=entry)  # instance=entry hace que se genere un form con la informacion que el objeto ya tenia, por lo tanto se puede editar
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)  # instancia un objeto form con la informacion que ya existia y no fue modificada (instance=entry) y la info agregada y/o modificada (segundo argumento)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


@login_required
def delete_entry(request, entry_id):
    """Delete an existing entry-"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_owner(request, topic)
    #entry.delete()
    return redirect('learning_logs:topic', topic_id=topic.id)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}  {# aca se carga la coleccion de templates que tiene bootstrap4 #}

<!DOCTYPE html>  {# se declara que es un archvo html ... #}
<html lang="en">  {# ...escrito en ingles #}
<head>  {# los archivos html se divien en head y body, el head le dice al browser lo que necesita para mostrar bien la pagina #}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Learning Log</title>  {# es lo que se muestra en la pestaña #}

  {% bootstrap_css %}  {# ambas lineas son cosas que trae bootstrap4 para que se vea mejor, ponele #}
  {% bootstrap_javascript jquery='full' %}  {# se ponen aca para usarlas en el body, creo #}
</head>
<body>  {# el body contiene lo que el usuario ve en la pagina #}
  {# se empieza escribiendo la barra de navegacion con nav, los que estan en verde son selectors, modifican la apariencia de items #}
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border"> {# en este caso le pone color al background, hace que se vea todo en hilera, que haya un margen, etc #}
    <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>  {# como esta primero va a ir arriba a la izquierda, este selector hace que resalte un toque del resto #}
    <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
        aria-laber="Toggle navigation">  {# todo esto hace que si se achica la ventana o se abre desde un dispositivo con pantalla chica los items de la barra desaparezcan y genera con boton con dichos items desplegables #}
        <span class="navbar-toggler-icon"></span></button>
    {# div es abreviacion de division, una pagina se crea dividiendola en secciones y definiendole a cada una cierta apariencia y comportamiento #}
    {# en este caso el div es para definir el boton con items desplegables cuando la pantalla sea mas chica y no entren todos los links en hilera #}
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">    {# bootstrap4 define los items de la barra de navegacion en ul (unerdered list), los selectors no se exactamente que hacen #}
        <li class="nav-item">             {# todo bijuterie para agregar el link a topics #}
        <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a></li>
      </ul>
      <ul class="navbar-nav ml-auto">  {# empiezan los set de links de users #}
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text">{{ user.username }}</span> {# span es como div, pero para partes mas chicas, en este caso solo para que el texto no se vea como un link #}
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>  {# el selector le da pinta de link y se agrega el link #}
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  {# el main se usa para la parte mas importante del body #}
  <main role="main" class="container">  {# se le asigna el selector de bootstrap4 container (un metodo simple para agrupar elementos) #}
    {# en este container se ubican dos div #}
    <div class="pb-2 mb-2 border-bottom">  {# en esta division se colocaran los titulos, los selectores son para darle espacio entre el titulo y el borde, entre dicho borde y los otros elementos y por ultimo se le asigna que haya borde abajo solamente #}
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>  {# aca se deja en blanco para que cada pagina tenga su propia apariencia #}
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>

</html>

learning_logs/templates/learning_logs/baseSinBtstrp.html
<p>
  <a href="{% url 'learning_logs:index' %}">Learning Log</a> -
  <a href="{% url 'learning_logs:topics' %}">Topics</a> -
  {% if user.is_authenticated %}  {# en el sistema de autenticacion de django todos los templates tienen una variable user que siempre tiene #}
    Hello, {{ user.username }}!   {# un atributo is_authenticated seteado: true si esta logeado y false si no #}
    <a href="{% url 'users:logout' %}">Log out</a>  {# el link de log out viene por defecto en django en las urls que inclui en urls de users #}
  {% else %}                                        {# se puede sobreescribir #}
    <a href="{% url 'users:register' %}">Register</a> -
    <a href="{% url 'users:login' %}">Log in</a>
  {% endif %}
</p>

  {% block content %}{% endblock content %}

learning_logs/templates/learning_logs/delete_entry.html
{% extends "learning_logs/base.html" %}
<p>Estas seguro? (german aprende a hacer un pop up por favor)</p>
<button name="submit">Si</button>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
{#topic.id le manda el id (generado automaticamente por django y conseguido con el metodo .id) al path en urls.py#}
  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
  <p>Edit entry:</p>
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}  {# se inicia el bloque page_header, lo llamamos desp en base.html #}
  <div class="jumbotron">  {# jumbotron es un selectot de bootstrap4, le pone onda a toda esta division #}
    <h1 class="display-3">Track your learning.</h1>  {# h1 es first-level header (titulo primario(? ) y el selector le da un thinner and taller look #}
    <p class="lead">Make your own Learning Log and keep a list of the
       topics you're learning about. Whenever you learn something new
       about a topic, make an entry summarizing what you've learned.</p>  {# p de parrafo ponele, y el selector hace mas claritas y altas las letras #}
    {% if user.is_authenticated %}
      <span class="navbar-text"}">Hello, {{ user.username }}!</span>
    {% else %}
      <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
         role="button">Register &raquo;</a>  {# todo para hacer un boton largo que representa un llamado a una accion. &raquo; es una entidad de html para escribir ">>" #}
    {% endif %}
  </div>

{% endblock page_header %}

learning_logs/templates/learning_logs/indexSinBtstrp.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p>Learning Log helps you keep track of your learning, for any topic you're learning about.</p>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
{% endblock page_header %}

{% block content %}
{# aca abajo aparece el method post, cuando se entra al link desde topic.html el metodo es get y cuando se oprime el boton submit se envia el form con la informacion completada denuevo a new_entry pero con el metodo post #}
  <p class="lead">Add a new entry:</p>
  <form class="form" action="{% url 'learning_logs:new_entry' topic.id %}" method='post'> {# aca tambien es manda el id para usarlo en las views.py para identificar el topic#}
    {% csrf_token %}  {# algo de seguridad de Django #}
    {% bootstrap_form form %}
    {% buttons %}
      <button class="btn btn-primary" name="submit">Add entry</button>
    {% endbuttons %}
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_entrySB.html
{% extends "learning_logs/base.html" %}
{# PAG 419 APROX #}
{% block content %}
{# topic.id le manda el id (generado automaticamente por django y conseguido con el metodo .id) al path en urls.py. #}
  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p> {# un link al topic, por eso necesito el topic id#}
{# aca abajo aparece el method post, cuando se entra al link desde topic.html el metodo es get y cuando se oprime el boton submit se envia el form con la informacion completada denuevo a new_entry pero con el metodo post #}
  <p>Add a new entry:</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'> {# aca tambien es manda el id para usarlo en las views.py para indentificar el topic#}
    {% csrf_token %} {# seguridad de django #}
    {{ form.as_p }} {# forma simple de mostrar un form, con .as_p se muestran los campos en formato de parrafo #}
    <button name="submit">Add entry</button>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h4>Add a new topic</h4>
{% endblock page_header %}

{% block content %}
  {# el "action" le indica al browser a donde mandar la informacion que recibe el form #}
  <form class="form" action="{% url 'learning_logs:new_topic' %}" method="post">
    {% csrf_token %}  {# algo de seguridad de Django #}
    {% bootstrap_form form %}
    {% buttons %}
      <button class="btn btn-primary" name="submit">Add topic</button>
    {% endbuttons %}
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topicSB.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p>Add a new topic:</p>
  {# el "action" le indica al browser a donde mandar la informacion que recibe el form #}
  <form action="{% url 'learning_logs:new_topic' %}" method='post'> {# en este caso se vuelve a mandar a new_topic pero con el metodo post (ver views.py) #}
    {% csrf_token %}  {# algo de seguridad de Django #}
    {{ form.as_p }}  {# forma simple de mostrar en pantalla todos los campos a llenar, .as_p muestra dichos campos en forma de parrafos #}
    <button name="submit">Add topic</button>  {# django no crea boton submit asi que hay que hacerlo #}
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
  <p>
    {#topic.id le manda el id (generado automaticamente por django y conseguido con el metodo .id) al path en urls.py#}
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
  </p>
  {%for entry in entries %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a></small>
      </h4>
      <div class="card-boddy">
        {{ entry.text|linebreaks }}
      </div>
    </div>
  {% empty %} {# si no hay entries muestra lo de abajo #}
    <p> There are no entries for this topic yet.</p>
  {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topicSinBtstrp.html
{% extends 'learning_logs/base.html' %}

{% block content %}

  <p>Topic: {{topic}}</p>  {# se usa topic ya que esta en el diccionario (context) que mandamos #}

  <p>Entries:</p>
  <p>
    {#topic.id le manda el id (generado automaticamente por django y conseguido con el metodo .id) al path en urls.py#}
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
  </p>
  <ul>  {# esto hace una bullet list con cada item entre los li de abajo#}
  {%for entry in entries %}
    <li>
      <p>{{ entry.date_added|date:'M d, Y H:i' }}</p> {# el pipe | hace que se modifiquen datos del template, en este caso para que el timestamp tenga el formato January 1, 2018 23:00 #}
      <p>{{ entry.text|linebreaks }}</p>  {# |linebreakes hace que los textos largos tengan un formato lindo y que entre todo bien o algo asi #}
      <p>
        <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a> - {# aca agarro el id del entry y lo mando en la request para que lo reciba en urls.py#}
        <a href="{% url 'learning_logs:delete_entry' entry.id %}">Delete entry</a>
      </p>
    </li>
  {% empty %} {# si no hay entries muestra lo de abajo #}
    <li> There are no entries for this topic yet.</li>
  {% endfor %}
  </ul>


{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h1>Topics</h1>
{% endblock page_header %}

{% block content %}
  <ul>
    {% for topic in topics %}
      <li><h3>
        {#topic.id le manda el id (generado automaticamente por django y conseguido con el metodo .id) al path en urls.py#}
          <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
      </h3></li>
    {% empty %}
      <li><h3>No topics have been added yet.</h3></li>
    {% endfor %}
  </ul>

  <h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a></h3>

{% endblock content %}

learning_logs/templates/learning_logs/topicsSinBtstrp.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p>Topics</p>

  <ul>
    {% for topic in topics %}
      <li>
        {#topic.id le manda el id (generado automaticamente por django y conseguido con el metodo .id) al path en urls.py#}
          <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
      </li>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>

  <a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>

{% endblock content %}